// מיפוי שם קבוצה עברי → אנגלי (שימוש בגילוי externalId)
// מועתק מ-frontend/src/utils/teamLogos.js
const HEBREW_TO_ENGLISH = {
  'ריאל מדריד': 'Real Madrid',
  'ברצלונה': 'Barcelona',
  'אטלטיקו מדריד': 'Atletico Madrid',
  'אתלטיק בילבאו': 'Athletic Bilbao',
  'ויאריאל': 'Villarreal',
  'בטיס': 'Real Betis',
  'סביליה': 'Sevilla',
  'ריאל סוסיאדד': 'Real Sociedad',
  'אספניול': 'Espanyol',
  'סלטה ויגו': 'Celta Vigo',
  'מיורקה': 'Mallorca',
  'ולנסיה': 'Valencia',
  "אלצ'ה": 'Elche',
  'ראיו': 'Rayo Vallecano',
  'לבאנטה': 'Levante',
  'אוססונה': 'Osasuna',
  "ג'ירונה": 'Girona',
  'חטאפה': 'Getafe',
  'לאס פלמאס': 'Las Palmas',
  'ויאדוליד': 'Real Valladolid',
  'אלאבס': 'Deportivo Alaves',
  'לגאנס': 'Leganes',
  'ליברפול': 'Liverpool',
  'ארסנל': 'Arsenal',
  "צ'לסי": 'Chelsea',
  'טוטנהאם': 'Tottenham',
  "מנצ'סטר סיטי": 'Manchester City',
  "מנצ'סטר יונייטד": 'Manchester United',
  'ניוקאסל': 'Newcastle United',
  'אסטון וילה': 'Aston Villa',
  'ווסטהאם': 'West Ham',
  'קריסטל פאלאס': 'Crystal Palace',
  'לידס': 'Leeds United',
  'ברנלי': 'Burnley',
  'סנדרלנד': 'Sunderland',
  'נוטינגהאם פורסט': 'Nottingham Forest',
  "בורנמות'": 'Bournemouth',
  'וולבס': 'Wolverhampton',
  'ברנטפורד': 'Brentford',
  'אינטר': 'Inter Milan',
  'יובנטוס': 'Juventus',
  'נאפולי': 'Napoli',
  'מילאן': 'AC Milan',
  'אטאלנטה': 'Atalanta',
  'רומא': 'AS Roma',
  'בולוניה': 'Bologna',
  'קומו': 'Como',
  'פיורנטינה': 'Fiorentina',
  'לאציו': 'Lazio',
  'טורינו': 'Torino',
  "ג'נואה": 'Genoa',
  'קליארי': 'Cagliari',
  'אודינזה': 'Udinese',
  'פארמה': 'Parma',
  'אמפולי': 'Empoli',
  'מונצה': 'Monza',
  'ורונה': 'Hellas Verona',
  "לצ'ה": 'Lecce',
  'ונציה': 'Venezia',
  'סאסואולו': 'Sassuolo',
  'סמפדוריה': 'Sampdoria',
  'באיירן מינכן': 'Bayern Munich',
  'דורטמונד': 'Borussia Dortmund',
  'לברקוזן': 'Bayer Leverkusen',
  'לייפציג': 'RB Leipzig',
  'שטוטגרט': 'Stuttgart',
  'פרנקפורט': 'Eintracht Frankfurt',
  'וולפסבורג': 'Wolfsburg',
  'פרייבורג': 'Freiburg',
  'הופנהיים': 'Hoffenheim',
  'מיינץ': 'Mainz',
  'מנשנגלדבאך': 'Borussia Monchengladbach',
  'אוניון ברלין': 'Union Berlin',
  'ורדר ברמן': 'Werder Bremen',
  'אוגסבורג': 'FC Augsburg',
  'קלן': 'FC Koln',
  'סנט פאולי': 'St Pauli',
  'היידנהיים': 'FC Heidenheim',
  'המבורג': 'Hamburg',
  "פריז סן ז'רמן": 'Paris Saint-Germain',
  'מרסיי': 'Marseille',
  'מונאקו': 'Monaco',
  'ליון': 'Lyon',
  'ליל': 'Lille',
  'ניס': 'Nice',
  'רן': 'Rennes',
  'לאנס': 'Lens',
  'ברסט': 'Brest',
  'סטרסבורג': 'Strasbourg',
  'טולוז': 'Toulouse',
  'נאנט': 'Nantes',
  "אנז'ה": 'Angers',
  'אוקסר': 'Auxerre',
  'לה האבר': 'Le Havre',
  'מץ': 'Metz',
  'לוריאן': 'Lorient',
  'פריז': 'Paris FC',
  'בנפיקה': 'Benfica',
  'ספורטינג ליסבון': 'Sporting Lisbon',
  'פורטו': 'FC Porto',
  'בראגה': 'Sporting Braga',
  'אייאקס': 'Ajax',
  'פ.ס.וו': 'PSV Eindhoven',
  'גלאטסראיי': 'Galatasaray',
  'בודה גלימט': 'Bodo Glimt',
  'סלביה פראג': 'Slavia Prague',
  'אולימפיאקוס': 'Olympiacos',
  "קלאב ברוז'": 'Club Brugge',
  'קראבג': 'Qarabag',
  'מכבי תל אביב': 'Maccabi Tel Aviv',
  'הפועל באר שבע': "Hapoel Be'er Sheva",
  'בית"ר ירושלים': 'Beitar Jerusalem',
  'הפועל תל אביב': 'Hapoel Tel-Aviv',
  'מכבי חיפה': 'Maccabi Haifa',
  'מכבי נתניה': 'Maccabi Netanya',
  'הפועל ירושלים': 'Hapoel Jerusalem',
  'הפועל חיפה': 'Hapoel Haifa',
  'עירוני קרית שמונה': 'Hapoel Ironi Kiryat Shmona',
  'עירוני טבריה': 'Ironi Tiberias',
  'בני סכנין': 'Bnei Sakhnin',
  'מ.ס. אשדוד': 'MS Ashdod',
  'הפועל פתח תקווה': 'Hapoel Petah Tikva',
  'הפועל פתח תקוה': 'Hapoel Petah Tikva',
  'מכבי בני ריינה': 'Maccabi Bnei Reineh'
};

// מנסה למצוא שם אנגלי לשם בעברית. מחזיר את השם המקורי אם לא מצא.
const hebrewToEnglish = (name) => {
  if (!name) return name;
  const direct = HEBREW_TO_ENGLISH[name];
  if (direct) return direct;
  // התאמה חלקית - חיפוש אם השם בעברית מופיע כתת-מחרוזת באחד מהמפתחות
  const norm = name.replace(/["'״׳]/g, '').trim();
  for (const [heb, eng] of Object.entries(HEBREW_TO_ENGLISH)) {
    const hebNorm = heb.replace(/["'״׳]/g, '').trim();
    if (hebNorm === norm) return eng;
  }
  return name;
};

module.exports = { hebrewToEnglish };
